// Generated by LiveScript 1.5.0
(function(){
  module.exports = function(System){
    return System.config({
      meta: {
        '*.ls': {
          loader: 'system-livescript'
        },
        '*.html': {
          loader: 'system-text'
        },
        '*.json': {
          loader: 'systemjs-plugin-json'
        }
      }
    });
  };
}).call(this);
